# Generated by Django 5.2.3 on 2025-06-27 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_cargos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.cargos'),
            preserve_default=False,
        ),
    ]
