# Generated by Django 5.2.3 on 2025-06-27 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_remove_pessoa_cargo_pessoa_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pessoa',
            name='projetos',
            field=models.ManyToManyField(to='crud.projetos'),
        ),
    ]
